import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import FontLoader from "./components/FontLoader";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
      >
        <FontLoader />
        {children}
      </body>
    </html>
  );
}
